<a href="https://colab.research.google.com/github/41371204h/1142-programming-language/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [44]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [45]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/16H5bD7lV9e2DBhR6Z0t-8Qq3Js4j07t_Q_hFz51oLpQ/edit?usp=sharing')

In [46]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期     時間 分類  品項  金額 付款人 地點 支付方式 備註
0  2026-03-05  10:50     吐司  20  自己      現金

In [47]:
import datetime

In [49]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

sort_str = input("請輸入分類: ")
item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
payer = input("請輸入付款人: ")
location = input("請輸入地點: ")
pay_method = input("請輸入支付方式: ")
note = input("請輸入備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-05
請輸入時間 (格式：HH:MM): 10:56
請輸入分類: 飲料
請輸入品項: 珍奶
請輸入金額: 60
請輸入付款人: 自己
請輸入地點: 學校
請輸入支付方式: 現金
請輸入備註: 無

In [50]:
date_str

'2026-03-05'

In [51]:
time_str

'10:56'

In [52]:
item

'珍奶'

In [53]:
amount

60.0

In [54]:
sort_str

'飲料'

In [55]:
payer

'自己'

In [56]:
location

'學校'

In [57]:
pay_method

'現金'

In [58]:
note

'無'

In [59]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': sort_str,
    '品項': item,
    '金額': amount,
    '付款人': payer,
    '地點': location,
    '支付方式': pay_method,
    '備註': note

}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [60]:
df

           日期     時間  分類  品項    金額 付款人  地點 支付方式 備註
0  2026-03-05  10:50      吐司    20  自己       現金
1  2026-03-05  10:56  飲料  珍奶  60.0  自己  學校   現金  無

In [61]:
data_to_write = new_data.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！